name = "shs-grades"
main = ".open-next/worker.js"
compatibility_date = "2026-08-10"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "shs-db"
database_id = "15462369-18fa-4cf4-9684-3c56e3538540"
migrations_dir = "migrations"

[vars]
BETTER_AUTH_URL = "https://shs-grades.innov-proj2026.workers.dev"
